/* =========================================================
   SHADHER GHOR - CATALOG DATA
   Authentic street food menu for Swader Ghor, Agartala.
   ========================================================= */

const APP_VERSION = "2.1.0";

/* `image` is an optional image URL. When empty/omitted the app falls back
   to the Font Awesome `icon` glyph on a themed background, so filling this
   in is entirely optional and safe to do incrementally, category by
   category or product by product. */
const CATEGORIES = [
  { id: "momo", name: "Momo", icon: "fa-solid fa-bowl-food", tag: "Steamed & fried", image: "" },
  { id: "chowmein", name: "Chowmein", icon: "fa-solid fa-utensils", tag: "Noodles & stir-fry", image: "" },
  { id: "biryani", name: "Biryani", icon: "fa-solid fa-utensil-spoon", tag: "Flavorful rice dishes", image: "" },
  { id: "burgers", name: "Burgers & Sandwiches", icon: "fa-solid fa-burger", tag: "Loaded & fresh", image: "" },
  { id: "rolls", name: "Rolls & Wraps", icon: "fa-solid fa-hotdog", tag: "Street-style rolls", image: "" },
  { id: "snacks", name: "Snacks & Sides", icon: "fa-solid fa-bacon", tag: "Perfect bites", image: "" },
  { id: "beverages", name: "Beverages", icon: "fa-solid fa-mug-saucer", tag: "Cool drinks & more", image: "" },
  { id: "combo", name: "Combo Meals", icon: "fa-solid fa-bag-shopping", tag: "Best value deals", image: "" },
];

const PRODUCTS = [

  /* ===================== MOMO COLLECTION ===================== */
  { id: "m1", name: "Classic Chicken Momo", desc: "Steamed chicken momos served with spicy tomato chutney and garlic dip.", category: "momo", rating: 4.8, badge: "Bestseller", icon: "fa-solid fa-bowl-food", image: "", basePrice: 100, sizes: [{ label: "1 Plate (6 pcs)", price: 100 }, { label: "1.5 Plate (9 pcs)", price: 150 }] },
  { id: "m2", name: "Paneer Momo", desc: "Steamed momos with a rich paneer filling, served with three chutneys.", category: "momo", rating: 4.7, badge: "Popular", icon: "fa-solid fa-bowl-food", image: "", basePrice: 120, sizes: [{ label: "1 Plate (6 pcs)", price: 120 }, { label: "1.5 Plate (9 pcs)", price: 180 }] },
  { id: "m3", name: "Veg Momo", desc: "Classic steamed momos with a mixed vegetable filling, light and fresh.", category: "momo", rating: 4.6, icon: "fa-solid fa-bowl-food", image: "", basePrice: 90, sizes: [{ label: "1 Plate (6 pcs)", price: 90 }, { label: "1.5 Plate (9 pcs)", price: 135 }] },
  { id: "m4", name: "Fried Chicken Momo", desc: "Crispy fried chicken momos with a spicy schezwan dip on the side.", category: "momo", rating: 4.7, badge: "Popular", icon: "fa-solid fa-bowl-food", image: "", basePrice: 120, sizes: [{ label: "1 Plate (6 pcs)", price: 120 }, { label: "1.5 Plate (9 pcs)", price: 180 }] },
  { id: "m5", name: "Kurkure Momo", desc: "Crispy coated fried momos with crunchy noodles on top, a fan favorite.", category: "momo", rating: 4.8, badge: "Bestseller", icon: "fa-solid fa-bowl-food", image: "", basePrice: 140, sizes: [{ label: "1 Plate (6 pcs)", price: 140 }, { label: "1.5 Plate (9 pcs)", price: 210 }] },
  { id: "m6", name: "Chicken Cheese Momo", desc: "Steamed momos with chicken and cheese filling, creamy and flavorful.", category: "momo", rating: 4.6, icon: "fa-solid fa-bowl-food", image: "", basePrice: 130, sizes: [{ label: "1 Plate (6 pcs)", price: 130 }, { label: "1.5 Plate (9 pcs)", price: 195 }] },

  /* ===================== CHOWMEIN COLLECTION ===================== */
  { id: "c1", name: "Chicken Hakka Noodles", desc: "Classic Hakka noodles stir-fried with chicken, veggies and soy sauce.", category: "chowmein", rating: 4.7, badge: "Bestseller", icon: "fa-solid fa-utensils", image: "", basePrice: 150, sizes: [{ label: "Half", price: 150 }, { label: "Full", price: 220 }] },
  { id: "c2", name: "Veg Hakka Noodles", desc: "Fresh stir-fried noodles with crunchy vegetables and aromatic spices.", category: "chowmein", rating: 4.6, icon: "fa-solid fa-utensils", image: "", basePrice: 120, sizes: [{ label: "Half", price: 120 }, { label: "Full", price: 180 }] },
  { id: "c3", name: "Schezwan Noodles", desc: "Spicy schezwan style noodles with chicken and extra veggies.", category: "chowmein", rating: 4.6, icon: "fa-solid fa-utensils", image: "", basePrice: 160, sizes: [{ label: "Half", price: 160 }, { label: "Full", price: 240 }] },
  { id: "c4", name: "Chicken Singapore Noodles", desc: "Curry-flavored rice noodles with chicken, shrimp and vegetables.", category: "chowmein", rating: 4.5, icon: "fa-solid fa-utensils", image: "", basePrice: 180, sizes: [{ label: "Half", price: 180 }, { label: "Full", price: 260 }] },

  /* ===================== BIRYANI COLLECTION ===================== */
  { id: "b1", name: "Chicken Biryani", desc: "Aromatic basmati rice layered with succulent chicken, herbs and spices.", category: "biryani", rating: 4.8, badge: "Bestseller", icon: "fa-solid fa-utensil-spoon", image: "", basePrice: 200, sizes: [{ label: "Half", price: 200 }, { label: "Full", price: 300 }] },
  { id: "b2", name: "Mutton Biryani", desc: "Tender mutton biryani with a rich, flavorful masala and fragrant rice.", category: "biryani", rating: 4.7, badge: "Popular", icon: "fa-solid fa-utensil-spoon", image: "", basePrice: 280, sizes: [{ label: "Half", price: 280 }, { label: "Full", price: 400 }] },
  { id: "b3", name: "Veg Biryani", desc: "Aromatic biryani with mixed vegetables, paneer and a hint of saffron.", category: "biryani", rating: 4.6, icon: "fa-solid fa-utensil-spoon", image: "", basePrice: 160, sizes: [{ label: "Half", price: 160 }, { label: "Full", price: 240 }] },
  { id: "b4", name: "Egg Biryani", desc: "Flavorful biryani with boiled eggs and layers of spiced rice.", category: "biryani", rating: 4.5, icon: "fa-solid fa-utensil-spoon", image: "", basePrice: 170, sizes: [{ label: "Half", price: 170 }, { label: "Full", price: 250 }] },
  { id: "b5", name: "Chicken Tikka Biryani", desc: "Biryani with marinated chicken tikka pieces, smoky and aromatic.", category: "biryani", rating: 4.7, icon: "fa-solid fa-utensil-spoon", image: "", basePrice: 250, sizes: [{ label: "Half", price: 250 }, { label: "Full", price: 360 }] },

  /* ===================== BURGERS & SANDWICHES ===================== */
  { id: "bu1", name: "Chicken Cheeseburger", desc: "Grilled chicken patty with cheese, lettuce, tomato and special sauce.", category: "burgers", rating: 4.7, badge: "Bestseller", icon: "fa-solid fa-burger", image: "", basePrice: 140, sizes: [{ label: "Single", price: 140 }, { label: "Double", price: 220 }] },
  { id: "bu2", name: "Veg Burger", desc: "Crispy veg patty with cheese, lettuce and house-made sauce.", category: "burgers", rating: 4.5, icon: "fa-solid fa-burger", image: "", basePrice: 110, sizes: [{ label: "Single", price: 110 }, { label: "Double", price: 180 }] },
  { id: "bu3", name: "Chicken Club Sandwich", desc: "Triple layer sandwich with grilled chicken, bacon, lettuce and tomato.", category: "burgers", rating: 4.6, icon: "fa-solid fa-burger", image: "", basePrice: 160, sizes: [{ label: "Regular", price: 160 }] },
  { id: "bu4", name: "Paneer Tikka Sandwich", desc: "Grilled paneer tikka with mint chutney and fresh vegetables.", category: "burgers", rating: 4.5, icon: "fa-solid fa-burger", image: "", basePrice: 130, sizes: [{ label: "Regular", price: 130 }] },

  /* ===================== ROLLS & WRAPS ===================== */
  { id: "r1", name: "Chicken Shawarma Roll", desc: "Juicy chicken shawarma with garlic sauce, wrapped in a soft roll.", category: "rolls", rating: 4.7, badge: "Popular", icon: "fa-solid fa-hotdog", image: "", basePrice: 120, sizes: [{ label: "Half", price: 120 }, { label: "Full", price: 180 }] },
  { id: "r2", name: "Paneer Tikka Roll", desc: "Grilled paneer tikka with mint sauce and crunchy onions in a wrap.", category: "rolls", rating: 4.6, icon: "fa-solid fa-hotdog", image: "", basePrice: 130, sizes: [{ label: "Half", price: 130 }, { label: "Full", price: 190 }] },
  { id: "r3", name: "Chicken Kathi Roll", desc: "Spicy chicken filling with eggs and onions in a paratha wrap.", category: "rolls", rating: 4.7, icon: "fa-solid fa-hotdog", image: "", basePrice: 140, sizes: [{ label: "Half", price: 140 }, { label: "Full", price: 200 }] },
  { id: "r4", name: "Veg Kathi Roll", desc: "Mixed vegetable filling with cheese and herbs in a paratha wrap.", category: "rolls", rating: 4.5, icon: "fa-solid fa-hotdog", image: "", basePrice: 110, sizes: [{ label: "Half", price: 110 }, { label: "Full", price: 160 }] },

  /* ===================== SNACKS & SIDES ===================== */
  { id: "s1", name: "Chicken Fry", desc: "Crispy fried chicken pieces with a spicy coating, served with dip.", category: "snacks", rating: 4.7, badge: "Bestseller", icon: "fa-solid fa-drumstick-bite", image: "", basePrice: 180, sizes: [{ label: "Half", price: 180 }, { label: "Full", price: 260 }] },
  { id: "s2", name: "French Fries", desc: "Crispy golden fries, lightly salted and served with ketchup.", category: "snacks", rating: 4.4, icon: "fa-solid fa-utensils", image: "", basePrice: 80, sizes: [{ label: "Half", price: 80 }, { label: "Full", price: 120 }] },
  { id: "s3", name: "Chicken Wings", desc: "Spicy chicken wings, fried to perfection with a smoky BBQ glaze.", category: "snacks", rating: 4.6, icon: "fa-solid fa-drumstick-bite", image: "", basePrice: 200, sizes: [{ label: "6 pcs", price: 200 }, { label: "12 pcs", price: 360 }] },
  { id: "s4", name: "Paneer Chilly", desc: "Crispy paneer tossed in a spicy chilly sauce with bell peppers.", category: "snacks", rating: 4.5, icon: "fa-solid fa-utensils", image: "", basePrice: 160, sizes: [{ label: "Half", price: 160 }, { label: "Full", price: 240 }] },
  { id: "s5", name: "Chicken Chilly", desc: "Boneless chicken pieces tossed in a spicy, tangy chilly sauce.", category: "snacks", rating: 4.6, icon: "fa-solid fa-utensils", image: "", basePrice: 190, sizes: [{ label: "Half", price: 190 }, { label: "Full", price: 280 }] },

  /* ===================== BEVERAGES ===================== */
  { id: "be1", name: "Sweet Lassi", desc: "Thick and creamy sweet lassi, a perfect complement to spicy food.", category: "beverages", rating: 4.5, icon: "fa-solid fa-mug-saucer", image: "", basePrice: 60, sizes: [{ label: "Small", price: 60 }, { label: "Large", price: 100 }] },
  { id: "be2", name: "Mango Lassi", desc: "Rich lassi with ripe mango pulp, sweet and refreshing.", category: "beverages", rating: 4.6, icon: "fa-solid fa-mug-saucer", image: "", basePrice: 80, sizes: [{ label: "Small", price: 80 }, { label: "Large", price: 130 }] },
  { id: "be3", name: "Cold Coffee", desc: "Chilled coffee with a hint of sweetness, topped with cream.", category: "beverages", rating: 4.4, icon: "fa-solid fa-mug-saucer", image: "", basePrice: 70, sizes: [{ label: "Small", price: 70 }, { label: "Large", price: 110 }] },
  { id: "be4", name: "Masala Chai", desc: "Classic Indian tea with aromatic spices, perfect any time of day.", category: "beverages", rating: 4.7, icon: "fa-solid fa-mug-saucer", image: "", basePrice: 30, sizes: [{ label: "Small", price: 30 }, { label: "Large", price: 50 }] },
  { id: "be5", name: "Fresh Lime Soda", desc: "Fresh lime juice with soda water and a hint of mint and salt.", category: "beverages", rating: 4.3, icon: "fa-solid fa-mug-saucer", image: "", basePrice: 50, sizes: [{ label: "Regular", price: 50 }] },

  /* ===================== COMBO MEALS ===================== */
  { id: "co1", name: "Momo Combo - 2 Plates", desc: "2 plates of any momo variety with extra chutney and a cold drink.", category: "combo", rating: 4.8, badge: "Popular", icon: "fa-solid fa-bag-shopping", image: "", basePrice: 220, sizes: [{ label: "Combo (2 plates + drink)", price: 220 }] },
  { id: "co2", name: "Biryani Combo", desc: "Biryani served with raita, salad and a cold drink of your choice.", category: "combo", rating: 4.7, icon: "fa-solid fa-bag-shopping", image: "", basePrice: 280, sizes: [{ label: "Combo (Biryani + sides + drink)", price: 280 }] },
  { id: "co3", name: "Chowmein + Chicken Fry Combo", desc: "Chicken chowmein served with crispy chicken fry and a drink.", category: "combo", rating: 4.8, badge: "Bestseller", icon: "fa-solid fa-bag-shopping", image: "", basePrice: 320, sizes: [{ label: "Combo (Chowmein + Fry + drink)", price: 320 }] },
  { id: "co4", name: "Burger + Fries Combo", desc: "Chicken burger with crispy fries and a cold drink.", category: "combo", rating: 4.6, icon: "fa-solid fa-bag-shopping", image: "", basePrice: 200, sizes: [{ label: "Combo (Burger + Fries + drink)", price: 200 }] },
  { id: "co5", name: "Snack Platter Combo", desc: "Chicken fry, wings, momos and fries - a perfect sharing platter.", category: "combo", rating: 4.7, icon: "fa-solid fa-bag-shopping", image: "", basePrice: 450, sizes: [{ label: "Large Platter (serves 2-3)", price: 450 }] },
  { id: "co6", name: "Roll + Lassi Combo", desc: "Any roll of your choice served with a sweet or mango lassi.", category: "combo", rating: 4.5, icon: "fa-solid fa-bag-shopping", image: "", basePrice: 180, sizes: [{ label: "Combo (Roll + Lassi)", price: 180 }] },
];

/* Delivery pricing is distance-based, calculated only from GPS
   coordinates (never from typed area/place names). BASE_DELIVERY_FEE
   covers the store's immediate vicinity (within BASE_DELIVERY_KM);
   beyond that, PER_KM_DELIVERY_RATE is charged for each additional km,
   rounded up. This applies to every payment method. */
const BASE_DELIVERY_FEE = 39;
const BASE_DELIVERY_KM = 3;
const PER_KM_DELIVERY_RATE = 12;
const FREE_DELIVERY_ABOVE = 499;

/* WhatsApp number */
const WHATSAPP_NUMBERS = {
  primary: "918794398516",
};

/* Phone (display) */
const PHONE_DISPLAY = "+91 87943 98516";
const PHONE_DIGITS = "918794398516";

/* UPI payment details (demo placeholder — replace with real UPI ID) */
const UPI_ID = "swaderghor@upi";
const UPI_PAYEE_NAME = "Swader Ghor";

/* Store & social links */
const STORE_NAME = "Swader Ghor";
const STORE_ADDRESS = "NH 108B, Radha Nagar, Agartala, Tripura 799001";
const STORE_LAT = 23.845906;
const STORE_LNG = 91.283050;
const MAP_LINK = "https://maps.app.goo.gl/qjv4cav9pDzmrN9o8";
const MAP_DIRECTIONS_LINK = "https://www.google.com/maps/dir/?api=1&destination=" + STORE_LAT + "," + STORE_LNG;
const GOOGLE_REVIEW_LINK = "https://maps.app.goo.gl/qjv4cav9pDzmrN9o8";
const INSTAGRAM_LINK = "https://www.instagram.com/swaderghor";
const FACEBOOK_LINK = "https://www.facebook.com/swaderghor";

/* Highlights shown on the home screen */
const HIGHLIGHTS = [
  { icon: "fa-solid fa-star", text: "Authentic recipes, fresh ingredients" },
  { icon: "fa-solid fa-truck-fast", text: "Fast & reliable delivery in Agartala" },
  { icon: "fa-solid fa-drumstick-bite", text: "Generous portions, honest prices" },
  { icon: "fa-solid fa-heart", text: "Made with love, served with pride" },
];

/* Special offers / promo banners */
const OFFERS = [
  { id: "off1", icon: "fa-solid fa-truck-fast", title: "Free Delivery", sub: "Automatically applied on all orders above ₹499", tag: "Auto-applied", theme: "green" },
  { id: "off2", icon: "fa-solid fa-gift", title: "Combo Deals", sub: "Get 15% off on all combo meals", tag: "Limited Time" },
  { id: "off3", icon: "fa-solid fa-bowl-food", title: "Weekend Special", sub: "Order 2 items and get a free drink", tag: "Weekend Only", theme: "green" },
];

/* =========================================================
   LANGUAGE / TRANSLATIONS
   Simple key -> string dictionary used by the language switcher.
   Only static UI chrome is translated; product data (names,
   descriptions) stays in English since the catalog is not localized.
   ========================================================= */
const LANGUAGES = [
  { code: "en", label: "English", native: "English" },
  { code: "bn", label: "Bengali", native: "বাংলা" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
];

const TRANSLATIONS = {
  en: {
    deliverTo: "Deliver to",
    heroEyebrow: "Freshly Made in Agartala. Always.",
    heroTitle1: "Your Cravings,",
    heroTitle2: "Freshly Served.",
    heroSub: "Authentic street food made with love, delivered across Agartala.",
    orderNow: "Order Now",
    searchPlaceholder: "Search for momo, biryani, burgers...",
    specialOffers: "Special Offers",
    craving: "What are you craving?",
    freeDelivery: "Free Delivery",
    freeDeliverySub: "On orders above ₹499",
    madeFresh: "Made Fresh",
    madeFreshSub: "Cooked on order day",
    bestsellers: "Bestsellers",
    rateUs: "Rate us on Google",
    aboutTitle: "Authentic Street Food, Fresh & Fast",
    aboutBody: "From sizzling momos to flavorful biryani, every dish at Swader Ghor is made with authentic recipes and the freshest ingredients.",
    onZomato: "On Zomato",
    onSwiggy: "On Swiggy",
    navHome: "Home",
    navMenu: "Menu",
    navCart: "Cart",
    navMore: "More",
    viewCart: "View Cart",
    proceedCheckout: "Proceed to Checkout",
    installTitle: "Install Swader Ghor",
    installSub: "Add to home screen for the full app experience",
    installBtn: "Install",
    installAppItem: "Install App",
    installAppItemSub: "Add to home screen",
    splashTag: "Authentic street food, fresh & fast",
    allItems: "All Items",
    all: "All",
    searchEmpty: "No items found. Try a different search.",
    searchMenuAria: "Search menu",
    clearSearchAria: "Clear search",
    selectSize: "Select Size / Portion",
    quantity: "Quantity",
    addToCart: "Add to Cart",
    addLabel: "ADD",
    totalForItems: "Total for {n} item",
    totalForItemsPlural: "Total for {n} items",
    ratingLabel: "rating",
    yourCart: "Your Cart",
    cartEmptyTitle: "Your cart feels light",
    cartEmptySub: "Add some delicious food items to get started",
    browseMenu: "Browse Menu",
    addNote: "Add a note for the chef",
    notePlaceholder: "E.g. Extra spicy, no onions, make it mild...",
    addTip: "Add a tip for our chefs",
    tipSub: "100% of your tip goes directly to the kitchen team",
    noTip: "No tip",
    tipOther: "Other",
    billDetails: "Bill Details",
    itemTotal: "Item Total",
    deliveryFee: "Delivery Fee",
    free: "FREE",
    tipForChefs: "Tip for Chefs",
    freeDeliveryDiscount: "Free Delivery Discount",
    toPay: "To Pay",
    addMoreForFreeDelivery: "Add {amount} more to get FREE delivery",
    unlockedFreeDelivery: "You unlocked FREE delivery on this order",
    paymentMethod: "Payment Method",
    cashOnDelivery: "Cash on Delivery",
    upiPayment: "UPI Payment",
    total: "TOTAL",
    deliveryLocationTitle: "Delivery Location",
    deliveryLocationDesc: "Enter your delivery area, or auto-detect it so we know where to send your food",
    autoDetectLocation: "Auto-detect my location",
    detectingLocation: "Detecting your location...",
    locationDetected: "Location detected!",
    orTypeManually: "or type manually",
    locationInputPlaceholder: "E.g. Krishna Nagar, Agartala, Tripura",
    saveLocation: "Save Location",
    or: "or",
    viewLocationOnMap: "View Our Location on Map",
    deliveryLocationAria: "Delivery location",
    deliveryCoordinatesLabel: "Delivery Coordinates",
    deliveryCoordinatesHint: "Auto-filled from GPS — you can edit it if the pin isn't quite right",
    coordinatesPlaceholder: "Latitude, Longitude",
    detectMyCoordinates: "Detect my coordinates",
    openInMaps: "Open in Maps",
    confirmOrder: "Confirm Your Order",
    yourDetails: "Your Details",
    fullName: "Full Name *",
    fullNamePlaceholder: "Enter your name",
    phoneNumber: "Phone Number *",
    phoneNumberPlaceholder: "10-digit mobile number",
    deliveryAddress: "Delivery Address *",
    deliveryAddressPlaceholder: "House no, street, landmark, area...",
    useMyLocation: "Use my current location",
    locationApplied: "Location applied",
    cityPincode: "City / Pincode",
    cityPincodePlaceholder: "City and pincode",
    preferredDateTime: "Preferred Delivery Date & Time",
    preferredDateTimePlaceholder: "E.g. 6 Sept, Evening 5-7 PM",
    ourLocation: "Our Location",
    openInGoogleMaps: "Open in Google Maps",
    orderSummary: "Order Summary",
    deliveryDistance: "Delivery Distance",
    pinLocationForAccuratePricing: "Pin your location for accurate pricing",
    codRateNote: "(₹{rate}/km)",
    tip: "Tip",
    totalAmount: "Total Amount",
    sendOrderViaWhatsapp: "Send Order Via WhatsApp",
    waHint: "We will confirm your order and payment details on WhatsApp within minutes.",
    sendOrderWhatsapp: "Send Order on WhatsApp",
    paymentMethodNote: "Payment method: {method}",
    orderSent: "Order Sent!",
    orderSentBody: "Your order details have been prepared. Please tap send in WhatsApp to complete your order, our team will confirm shortly.",
    backHome: "Back to Home",
    chatWithUs: "Chat With Us",
    moreTitle: "Swader Ghor",
    ratedOnGoogle: "Rated on Google",
    callUs: "Call Us",
    whatsapp: "WhatsApp",
    ourLocationItem: "Our Location",
    viewOnMaps: "View on Google Maps",
    rateUsOnGoogle: "Rate Us on Google",
    rateUsOnGoogleSub: "Tell others what you loved",
    instagram: "Instagram",
    facebook: "Facebook",
    customCateringEnquiry: "Custom Catering Enquiry",
    customCateringEnquirySub: "Tell us about your event",
    appVersionLabel: "Swader Ghor App · Version {version}",
    contactUs: "Contact Us",
    call: "Call",
    directions: "Directions",
    googleMaps: "Google Maps",
    followUs: "Follow us",
    languageTitle: "Language",
    languageDesc: "Choose your preferred language for the app",
    areYouSure: "Are you sure?",
    cannotBeUndone: "This action cannot be undone.",
    cancel: "Cancel",
    confirm: "Confirm",
    clearCartTitle: "Clear your cart?",
    clearCartMessage: "This will remove all items from your cart. This action cannot be undone.",
    clearCartConfirm: "Clear Cart",
    payViaUpi: "Pay via UPI",
    payViaUpiDesc: "Scan the QR code or copy the UPI ID below to pay, then place your order — we'll confirm your payment on WhatsApp.",
    demoQrLabel: "Demo QR · Replace with real UPI QR",
    upiIdLabel: "UPI ID",
    phoneNumberLabel: "Phone Number",
    copy: "Copy",
    copied: "Copied",
    gotItContinue: "Got it, Continue",
    customEnquiryTitle: "Custom Catering Enquiry",
    customEnquiryDesc: "Tell us about your event and we'll get back to you on WhatsApp with a custom menu and price.",
    eventType: "Event Type",
    birthdayParty: "Birthday Party",
    corporateEvent: "Corporate Event",
    wedding: "Wedding",
    houseParty: "House Party",
    otherOccasion: "Other",
    dishesInterested: "Dishes You're Interested In",
    dishesInterestedPlaceholder: "e.g. Momo platter, Biryani, Chowmein, Burgers...",
    numberOfPeople: "Number of People",
    numberOfPeoplePlaceholder: "e.g. 20-25 people",
    preferredDateTimeLabel: "Preferred Date & Time",
    chooseDate: "Choose date",
    chooseTime: "Choose time",
    specialInstructions: "Special Instructions",
    optional: "Optional",
    specialInstructionsPlaceholder: "Dietary restrictions, preferred cuisine, delivery notes, etc.",
    sendEnquiryWhatsapp: "Send Enquiry on WhatsApp",
    toastAddedToCart: "{name} added to cart",
    toastItemRemoved: "Item removed",
    toastCartCleared: "Cart cleared",
    toastFillDetails: "Please fill in name, phone and address",
    toastInvalidPhone: "Please enter a valid 10-digit phone number",
    toastCartEmptyRetry: "Your cart is empty. Please add items again.",
    toastEnterLocation: "Please enter your location",
    toastLocationSaved: "Location saved",
    toastNoGeolocation: "Location services aren't supported on this device",
    toastLocationUpdated: "Location updated: {label}",
    toastLocationDenied: "Please allow location access to auto-detect",
    toastLocationFailed: "Couldn't detect location, try entering it manually",
    toastAppAlreadyInstalled: "App already installed or not supported on this browser",
    toastInstalling: "Installing Swader Ghor...",
    toastOpeningWhatsappEnquiry: "Opening WhatsApp with your enquiry...",
    toastLanguageUpdated: "Language updated",
    toastDemoQr: "Demo QR — replace with your real UPI QR code",
    toastCopied: "Copied to clipboard",
    toastCopyFailed: "Couldn't copy — please copy it manually",
    toastInstalled: "Swader Ghor installed successfully!",
    toastNewVersion: "New version available",
    toastTapToRefresh: "Tap to refresh",
    toastCoordsInvalid: "Please enter valid coordinates as \"lat, lng\"",
    toastCoordsUpdated: "Delivery coordinates updated",
    totalLabel: "TOTAL",
    decreaseQtyAria: "Decrease quantity",
    increaseQtyAria: "Increase quantity",
    itemCount: "{n} item",
    itemCountPlural: "{n} items",
    onwards: "onwards",
  },
  bn: {
    deliverTo: "ডেলিভারি ঠিকানা",
    heroEyebrow: "আগরতলায় তাজা তৈরি। সবসময়।",
    heroTitle1: "আপনার পছন্দের খাবার,",
    heroTitle2: "তাজা পরিবেশিত।",
    heroSub: "ভালোবাসা দিয়ে তৈরি খাঁটি স্ট্রিট ফুড, সারা আগরতলায় পৌঁছে দেওয়া হয়।",
    orderNow: "অর্ডার করুন",
    searchPlaceholder: "মোমো, বিরিয়ানি, বার্গার খুঁজুন...",
    specialOffers: "বিশেষ অফার",
    craving: "আজ কী খেতে ইচ্ছে করছে?",
    freeDelivery: "ফ্রি ডেলিভারি",
    freeDeliverySub: "৪৯৯ টাকার বেশি অর্ডারে",
    madeFresh: "তাজা তৈরি",
    madeFreshSub: "অর্ডারের দিনেই রান্না করা হয়",
    bestsellers: "জনপ্রিয় খাবার",
    rateUs: "গুগলে আমাদের রেট করুন",
    aboutTitle: "খাঁটি স্ট্রিট ফুড, তাজা ও দ্রুত",
    aboutBody: "মোমো থেকে সুস্বাদু বিরিয়ানি পর্যন্ত, সোয়াদের ঘরের প্রতিটি খাবার তৈরি হয় খাঁটি রেসিপি ও সতেজ উপকরণ দিয়ে।",
    onZomato: "জোম্যাটোতে",
    onSwiggy: "সুইগিতে",
    navHome: "হোম",
    navMenu: "মেনু",
    navCart: "কার্ট",
    navMore: "আরও",
    viewCart: "কার্ট দেখুন",
    proceedCheckout: "চেকআউট করুন",
    installTitle: "সোয়াদের ঘর ইনস্টল করুন",
    installSub: "সম্পূর্ণ অ্যাপ অভিজ্ঞতার জন্য হোম স্ক্রিনে যোগ করুন",
    installBtn: "ইনস্টল করুন",
    installAppItem: "অ্যাপ ইনস্টল করুন",
    installAppItemSub: "হোম স্ক্রিনে যোগ করুন",
    splashTag: "খাঁটি স্ট্রিট ফুড, তাজা ও দ্রুত",
    allItems: "সব আইটেম",
    all: "সব",
    searchEmpty: "কোনো আইটেম পাওয়া যায়নি। অন্য কিছু খুঁজে দেখুন।",
    searchMenuAria: "মেনু খুঁজুন",
    clearSearchAria: "খোঁজ মুছুন",
    selectSize: "সাইজ / পোরশন নির্বাচন করুন",
    quantity: "পরিমাণ",
    addToCart: "কার্টে যোগ করুন",
    addLabel: "যোগ করুন",
    totalForItems: "{n}টি আইটেমের মোট",
    totalForItemsPlural: "{n}টি আইটেমের মোট",
    ratingLabel: "রেটিং",
    yourCart: "আপনার কার্ট",
    cartEmptyTitle: "আপনার কার্ট খালি",
    cartEmptySub: "শুরু করতে সুস্বাদু খাবার যোগ করুন",
    browseMenu: "মেনু দেখুন",
    addNote: "শেফের জন্য একটি নোট যোগ করুন",
    notePlaceholder: "যেমন: বেশি ঝাল, পেঁয়াজ ছাড়া, হালকা মশলা...",
    addTip: "আমাদের শেফদের জন্য টিপ দিন",
    tipSub: "আপনার টিপের ১০০% সরাসরি রান্নাঘরের দলের কাছে যায়",
    noTip: "টিপ নেই",
    tipOther: "অন্যান্য",
    billDetails: "বিলের বিবরণ",
    itemTotal: "মোট আইটেম মূল্য",
    deliveryFee: "ডেলিভারি ফি",
    free: "ফ্রি",
    tipForChefs: "শেফদের জন্য টিপ",
    freeDeliveryDiscount: "ফ্রি ডেলিভারি ছাড়",
    toPay: "মোট প্রদেয়",
    addMoreForFreeDelivery: "ফ্রি ডেলিভারি পেতে আরও {amount} যোগ করুন",
    unlockedFreeDelivery: "আপনি এই অর্ডারে ফ্রি ডেলিভারি আনলক করেছেন",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    cashOnDelivery: "ক্যাশ অন ডেলিভারি",
    upiPayment: "ইউপিআই পেমেন্ট",
    total: "মোট",
    deliveryLocationTitle: "ডেলিভারি অবস্থান",
    deliveryLocationDesc: "আপনার ডেলিভারি এলাকা লিখুন, অথবা স্বয়ংক্রিয়ভাবে সনাক্ত করুন যাতে আমরা জানি কোথায় খাবার পাঠাতে হবে",
    autoDetectLocation: "আমার অবস্থান স্বয়ংক্রিয়ভাবে সনাক্ত করুন",
    detectingLocation: "আপনার অবস্থান সনাক্ত করা হচ্ছে...",
    locationDetected: "অবস্থান সনাক্ত হয়েছে!",
    orTypeManually: "অথবা নিজে টাইপ করুন",
    locationInputPlaceholder: "যেমন: কৃষ্ণনগর, আগরতলা, ত্রিপুরা",
    saveLocation: "অবস্থান সংরক্ষণ করুন",
    or: "অথবা",
    viewLocationOnMap: "মানচিত্রে আমাদের অবস্থান দেখুন",
    deliveryLocationAria: "ডেলিভারি অবস্থান",
    deliveryCoordinatesLabel: "ডেলিভারি স্থানাঙ্ক",
    deliveryCoordinatesHint: "জিপিএস থেকে স্বয়ংক্রিয়ভাবে পূরণ হয়েছে — পিন সঠিক না হলে সম্পাদনা করতে পারেন",
    coordinatesPlaceholder: "অক্ষাংশ, দ্রাঘিমাংশ",
    detectMyCoordinates: "আমার স্থানাঙ্ক সনাক্ত করুন",
    openInMaps: "মানচিত্রে খুলুন",
    confirmOrder: "আপনার অর্ডার নিশ্চিত করুন",
    yourDetails: "আপনার বিবরণ",
    fullName: "পূর্ণ নাম *",
    fullNamePlaceholder: "আপনার নাম লিখুন",
    phoneNumber: "ফোন নম্বর *",
    phoneNumberPlaceholder: "১০-সংখ্যার মোবাইল নম্বর",
    deliveryAddress: "ডেলিভারি ঠিকানা *",
    deliveryAddressPlaceholder: "বাড়ি নং, রাস্তা, ল্যান্ডমার্ক, এলাকা...",
    useMyLocation: "আমার বর্তমান অবস্থান ব্যবহার করুন",
    locationApplied: "অবস্থান প্রয়োগ হয়েছে",
    cityPincode: "শহর / পিনকোড",
    cityPincodePlaceholder: "শহর এবং পিনকোড",
    preferredDateTime: "পছন্দের ডেলিভারি তারিখ ও সময়",
    preferredDateTimePlaceholder: "যেমন: ৬ সেপ্টেম্বর, সন্ধ্যা ৫-৭টা",
    ourLocation: "আমাদের অবস্থান",
    openInGoogleMaps: "গুগল ম্যাপে খুলুন",
    orderSummary: "অর্ডার সারাংশ",
    deliveryDistance: "ডেলিভারি দূরত্ব",
    pinLocationForAccuratePricing: "সঠিক মূল্যের জন্য আপনার অবস্থান পিন করুন",
    codRateNote: "(₹{rate}/কিমি)",
    tip: "টিপ",
    totalAmount: "মোট পরিমাণ",
    sendOrderViaWhatsapp: "হোয়াটসঅ্যাপের মাধ্যমে অর্ডার পাঠান",
    waHint: "আমরা কয়েক মিনিটের মধ্যে হোয়াটসঅ্যাপে আপনার অর্ডার ও পেমেন্ট বিবরণ নিশ্চিত করব।",
    sendOrderWhatsapp: "হোয়াটসঅ্যাপে অর্ডার পাঠান",
    paymentMethodNote: "পেমেন্ট পদ্ধতি: {method}",
    orderSent: "অর্ডার পাঠানো হয়েছে!",
    orderSentBody: "আপনার অর্ডারের বিবরণ প্রস্তুত করা হয়েছে। অর্ডার সম্পূর্ণ করতে হোয়াটসঅ্যাপে পাঠান চাপুন, আমাদের দল শীঘ্রই নিশ্চিত করবে।",
    backHome: "হোমে ফিরে যান",
    chatWithUs: "আমাদের সাথে চ্যাট করুন",
    moreTitle: "সোয়াদের ঘর",
    ratedOnGoogle: "গুগলে রেটেড",
    callUs: "আমাদের কল করুন",
    whatsapp: "হোয়াটসঅ্যাপ",
    ourLocationItem: "আমাদের অবস্থান",
    viewOnMaps: "গুগল ম্যাপে দেখুন",
    rateUsOnGoogle: "গুগলে আমাদের রেট করুন",
    rateUsOnGoogleSub: "আপনি যা পছন্দ করেছেন তা অন্যদের বলুন",
    instagram: "ইনস্টাগ্রাম",
    facebook: "ফেসবুক",
    customCateringEnquiry: "কাস্টম ক্যাটারিং অনুসন্ধান",
    customCateringEnquirySub: "আপনার অনুষ্ঠান সম্পর্কে আমাদের বলুন",
    appVersionLabel: "সোয়াদের ঘর অ্যাপ · সংস্করণ {version}",
    contactUs: "যোগাযোগ করুন",
    call: "কল করুন",
    directions: "দিকনির্দেশ",
    googleMaps: "গুগল ম্যাপ",
    followUs: "ফলো করুন",
    languageTitle: "ভাষা",
    languageDesc: "অ্যাপের জন্য আপনার পছন্দের ভাষা বেছে নিন",
    areYouSure: "আপনি কি নিশ্চিত?",
    cannotBeUndone: "এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।",
    cancel: "বাতিল",
    confirm: "নিশ্চিত করুন",
    clearCartTitle: "আপনার কার্ট খালি করবেন?",
    clearCartMessage: "এটি আপনার কার্ট থেকে সব আইটেম সরিয়ে দেবে। এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।",
    clearCartConfirm: "কার্ট খালি করুন",
    payViaUpi: "ইউপিআই এর মাধ্যমে পেমেন্ট করুন",
    payViaUpiDesc: "পেমেন্ট করতে কিউআর কোড স্ক্যান করুন অথবা নিচের ইউপিআই আইডি কপি করুন, তারপর অর্ডার দিন — আমরা হোয়াটসঅ্যাপে আপনার পেমেন্ট নিশ্চিত করব।",
    demoQrLabel: "ডেমো কিউআর · আসল ইউপিআই কিউআর দিয়ে প্রতিস্থাপন করুন",
    upiIdLabel: "ইউপিআই আইডি",
    phoneNumberLabel: "ফোন নম্বর",
    copy: "কপি করুন",
    copied: "কপি হয়েছে",
    gotItContinue: "বুঝেছি, চালিয়ে যান",
    customEnquiryTitle: "কাস্টম ক্যাটারিং অনুসন্ধান",
    customEnquiryDesc: "আপনার অনুষ্ঠান সম্পর্কে আমাদের বলুন এবং আমরা কাস্টম মেনু ও মূল্য নিয়ে হোয়াটসঅ্যাপে যোগাযোগ করব।",
    eventType: "অনুষ্ঠানের ধরন",
    birthdayParty: "জন্মদিনের অনুষ্ঠান",
    corporateEvent: "কর্পোরেট ইভেন্ট",
    wedding: "বিবাহ",
    houseParty: "হাউস পার্টি",
    otherOccasion: "অন্যান্য",
    dishesInterested: "আপনি যে পদগুলিতে আগ্রহী",
    dishesInterestedPlaceholder: "যেমন: মোমো প্লেট, বিরিয়ানি, চাউমিন, বার্গার...",
    numberOfPeople: "মানুষের সংখ্যা",
    numberOfPeoplePlaceholder: "যেমন: ২০-২৫ জন",
    preferredDateTimeLabel: "পছন্দের তারিখ ও সময়",
    chooseDate: "তারিখ বেছে নিন",
    chooseTime: "সময় বেছে নিন",
    specialInstructions: "বিশেষ নির্দেশনা",
    optional: "ঐচ্ছিক",
    specialInstructionsPlaceholder: "খাদ্য বিধিনিষেধ, পছন্দের রান্না, ডেলিভারি নোট ইত্যাদি।",
    sendEnquiryWhatsapp: "হোয়াটসঅ্যাপে অনুসন্ধান পাঠান",
    toastAddedToCart: "{name} কার্টে যোগ হয়েছে",
    toastItemRemoved: "আইটেম সরানো হয়েছে",
    toastCartCleared: "কার্ট খালি করা হয়েছে",
    toastFillDetails: "অনুগ্রহ করে নাম, ফোন এবং ঠিকানা পূরণ করুন",
    toastInvalidPhone: "অনুগ্রহ করে একটি বৈধ ১০-সংখ্যার ফোন নম্বর লিখুন",
    toastCartEmptyRetry: "আপনার কার্ট খালি। অনুগ্রহ করে আবার আইটেম যোগ করুন।",
    toastEnterLocation: "অনুগ্রহ করে আপনার অবস্থান লিখুন",
    toastLocationSaved: "অবস্থান সংরক্ষিত হয়েছে",
    toastNoGeolocation: "এই ডিভাইসে অবস্থান পরিষেবা সমর্থিত নয়",
    toastLocationUpdated: "অবস্থান আপডেট হয়েছে: {label}",
    toastLocationDenied: "স্বয়ংক্রিয় সনাক্তকরণের জন্য অনুগ্রহ করে অবস্থান অ্যাক্সেসের অনুমতি দিন",
    toastLocationFailed: "অবস্থান সনাক্ত করা যায়নি, নিজে লিখে চেষ্টা করুন",
    toastAppAlreadyInstalled: "অ্যাপটি ইতিমধ্যে ইনস্টল করা আছে অথবা এই ব্রাউজারে সমর্থিত নয়",
    toastInstalling: "সোয়াদের ঘর ইনস্টল হচ্ছে...",
    toastOpeningWhatsappEnquiry: "আপনার অনুসন্ধান নিয়ে হোয়াটসঅ্যাপ খোলা হচ্ছে...",
    toastLanguageUpdated: "ভাষা আপডেট হয়েছে",
    toastDemoQr: "ডেমো কিউআর — আপনার আসল ইউপিআই কিউআর কোড দিয়ে প্রতিস্থাপন করুন",
    toastCopied: "ক্লিপবোর্ডে কপি হয়েছে",
    toastCopyFailed: "কপি করা যায়নি — অনুগ্রহ করে ম্যানুয়ালি কপি করুন",
    toastInstalled: "সোয়াদের ঘর সফলভাবে ইনস্টল হয়েছে!",
    toastNewVersion: "নতুন সংস্করণ পাওয়া যাচ্ছে",
    toastTapToRefresh: "রিফ্রেশ করতে ট্যাপ করুন",
    toastCoordsInvalid: "অনুগ্রহ করে \"lat, lng\" আকারে বৈধ স্থানাঙ্ক লিখুন",
    toastCoordsUpdated: "ডেলিভারি স্থানাঙ্ক আপডেট হয়েছে",
    totalLabel: "মোট",
    decreaseQtyAria: "পরিমাণ কমান",
    increaseQtyAria: "পরিমাণ বাড়ান",
    itemCount: "{n}টি আইটেম",
    itemCountPlural: "{n}টি আইটেম",
    onwards: "থেকে শুরু",
  },
  hi: {
    deliverTo: "डिलीवरी पता",
    heroEyebrow: "अगरतला में हमेशा ताज़ा बना।",
    heroTitle1: "आपकी पसंदीदा क्रेविंग,",
    heroTitle2: "ताज़ा परोसी गई।",
    heroSub: "प्यार से बना असली स्ट्रीट फूड, पूरे अगरतला में डिलीवर किया जाता है।",
    orderNow: "अभी ऑर्डर करें",
    searchPlaceholder: "मोमो, बिरयानी, बर्गर खोजें...",
    specialOffers: "विशेष ऑफर",
    craving: "आज क्या खाने का मन है?",
    freeDelivery: "मुफ़्त डिलीवरी",
    freeDeliverySub: "₹499 से ऊपर के ऑर्डर पर",
    madeFresh: "ताज़ा बना",
    madeFreshSub: "ऑर्डर वाले दिन ही पकाया गया",
    bestsellers: "पसंदीदा व्यंजन",
    rateUs: "गूगल पर हमें रेट करें",
    aboutTitle: "असली स्ट्रीट फूड, ताज़ा और तेज़",
    aboutBody: "मोमो से लेकर स्वादिष्ट बिरयानी तक, स्वादेर घर की हर डिश असली रेसिपी और ताज़ी सामग्री से बनाई जाती है।",
    onZomato: "ज़ोमैटो पर",
    onSwiggy: "स्विगी पर",
    navHome: "होम",
    navMenu: "मेन्यू",
    navCart: "कार्ट",
    navMore: "और",
    viewCart: "कार्ट देखें",
    proceedCheckout: "चेकआउट करें",
    installTitle: "स्वादेर घर इंस्टॉल करें",
    installSub: "पूरे ऐप अनुभव के लिए होम स्क्रीन पर जोड़ें",
    installBtn: "इंस्टॉल करें",
    installAppItem: "ऐप इंस्टॉल करें",
    installAppItemSub: "होम स्क्रीन पर जोड़ें",
    splashTag: "असली स्ट्रीट फूड, ताज़ा और तेज़",
    allItems: "सभी आइटम",
    all: "सभी",
    searchEmpty: "कोई आइटम नहीं मिला। कुछ और खोजें।",
    searchMenuAria: "मेन्यू खोजें",
    clearSearchAria: "खोज साफ़ करें",
    selectSize: "साइज़ / पोर्शन चुनें",
    quantity: "मात्रा",
    addToCart: "कार्ट में जोड़ें",
    addLabel: "जोड़ें",
    totalForItems: "{n} आइटम का कुल",
    totalForItemsPlural: "{n} आइटम का कुल",
    ratingLabel: "रेटिंग",
    yourCart: "आपका कार्ट",
    cartEmptyTitle: "आपका कार्ट खाली है",
    cartEmptySub: "शुरू करने के लिए स्वादिष्ट भोजन जोड़ें",
    browseMenu: "मेन्यू देखें",
    addNote: "शेफ के लिए एक नोट जोड़ें",
    notePlaceholder: "जैसे: अधिक तीखा, प्याज़ नहीं, हल्का मसाला...",
    addTip: "हमारे शेफ के लिए टिप दें",
    tipSub: "आपकी टिप का 100% सीधे किचन टीम को जाता है",
    noTip: "कोई टिप नहीं",
    tipOther: "अन्य",
    billDetails: "बिल विवरण",
    itemTotal: "आइटम कुल",
    deliveryFee: "डिलीवरी शुल्क",
    free: "मुफ़्त",
    tipForChefs: "शेफ के लिए टिप",
    freeDeliveryDiscount: "मुफ़्त डिलीवरी छूट",
    toPay: "कुल भुगतान",
    addMoreForFreeDelivery: "मुफ़्त डिलीवरी पाने के लिए {amount} और जोड़ें",
    unlockedFreeDelivery: "आपने इस ऑर्डर पर मुफ़्त डिलीवरी अनलॉक कर ली है",
    paymentMethod: "भुगतान का तरीका",
    cashOnDelivery: "कैश ऑन डिलीवरी",
    upiPayment: "यूपीआई भुगतान",
    total: "कुल",
    deliveryLocationTitle: "डिलीवरी स्थान",
    deliveryLocationDesc: "अपना डिलीवरी क्षेत्र दर्ज करें, या स्वतः पता लगाएं ताकि हमें पता चले कि आपका खाना कहाँ भेजना है",
    autoDetectLocation: "मेरा स्थान स्वतः पता लगाएं",
    detectingLocation: "आपका स्थान पता लगाया जा रहा है...",
    locationDetected: "स्थान का पता चल गया!",
    orTypeManually: "या स्वयं टाइप करें",
    locationInputPlaceholder: "जैसे: कृष्णा नगर, अगरतला, त्रिपुरा",
    saveLocation: "स्थान सहेजें",
    or: "या",
    viewLocationOnMap: "मानचित्र पर हमारा स्थान देखें",
    deliveryLocationAria: "डिलीवरी स्थान",
    deliveryCoordinatesLabel: "डिलीवरी निर्देशांक",
    deliveryCoordinatesHint: "जीपीएस से स्वतः भरा गया — यदि पिन सही नहीं है तो आप इसे संपादित कर सकते हैं",
    coordinatesPlaceholder: "अक्षांश, देशांतर",
    detectMyCoordinates: "मेरे निर्देशांक पता लगाएं",
    openInMaps: "मानचित्र में खोलें",
    confirmOrder: "अपना ऑर्डर कन्फर्म करें",
    yourDetails: "आपका विवरण",
    fullName: "पूरा नाम *",
    fullNamePlaceholder: "अपना नाम दर्ज करें",
    phoneNumber: "फ़ोन नंबर *",
    phoneNumberPlaceholder: "10-अंकीय मोबाइल नंबर",
    deliveryAddress: "डिलीवरी पता *",
    deliveryAddressPlaceholder: "मकान नंबर, सड़क, लैंडमार्क, क्षेत्र...",
    useMyLocation: "मेरा वर्तमान स्थान उपयोग करें",
    locationApplied: "स्थान लागू किया गया",
    cityPincode: "शहर / पिनकोड",
    cityPincodePlaceholder: "शहर और पिनकोड",
    preferredDateTime: "पसंदीदा डिलीवरी तारीख और समय",
    preferredDateTimePlaceholder: "जैसे: 6 सितंबर, शाम 5-7 बजे",
    ourLocation: "हमारा स्थान",
    openInGoogleMaps: "गूगल मैप्स में खोलें",
    orderSummary: "ऑर्डर सारांश",
    deliveryDistance: "डिलीवरी दूरी",
    pinLocationForAccuratePricing: "सटीक कीमत के लिए अपना स्थान पिन करें",
    codRateNote: "(₹{rate}/किमी)",
    tip: "टिप",
    totalAmount: "कुल राशि",
    sendOrderViaWhatsapp: "व्हाट्सएप के ज़रिए ऑर्डर भेजें",
    waHint: "हम कुछ ही मिनटों में व्हाट्सएप पर आपके ऑर्डर और भुगतान विवरण की पुष्टि करेंगे।",
    sendOrderWhatsapp: "व्हाट्सएप पर ऑर्डर भेजें",
    paymentMethodNote: "भुगतान का तरीका: {method}",
    orderSent: "ऑर्डर भेज दिया गया!",
    orderSentBody: "आपके ऑर्डर का विवरण तैयार कर लिया गया है। ऑर्डर पूरा करने के लिए व्हाट्सएप में भेजें दबाएं, हमारी टीम जल्द ही पुष्टि करेगी।",
    backHome: "होम पर वापस जाएं",
    chatWithUs: "हमसे चैट करें",
    moreTitle: "स्वादेर घर",
    ratedOnGoogle: "गूगल पर रेटेड",
    callUs: "हमें कॉल करें",
    whatsapp: "व्हाट्सएप",
    ourLocationItem: "हमारा स्थान",
    viewOnMaps: "गूगल मैप्स पर देखें",
    rateUsOnGoogle: "गूगल पर हमें रेट करें",
    rateUsOnGoogleSub: "दूसरों को बताएं आपको क्या पसंद आया",
    instagram: "इंस्टाग्राम",
    facebook: "फेसबुक",
    customCateringEnquiry: "कस्टम केटरिंग पूछताछ",
    customCateringEnquirySub: "अपने इवेंट के बारे में हमें बताएं",
    appVersionLabel: "स्वादेर घर ऐप · संस्करण {version}",
    contactUs: "संपर्क करें",
    call: "कॉल करें",
    directions: "दिशा-निर्देश",
    googleMaps: "गूगल मैप्स",
    followUs: "फॉलो करें",
    languageTitle: "भाषा",
    languageDesc: "ऐप के लिए अपनी पसंदीदा भाषा चुनें",
    areYouSure: "क्या आप सुनिश्चित हैं?",
    cannotBeUndone: "यह कार्रवाई पूर्ववत नहीं की जा सकती।",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    clearCartTitle: "अपना कार्ट खाली करें?",
    clearCartMessage: "इससे आपके कार्ट से सभी आइटम हट जाएंगे। यह कार्रवाई पूर्ववत नहीं की जा सकती।",
    clearCartConfirm: "कार्ट खाली करें",
    payViaUpi: "यूपीआई से भुगतान करें",
    payViaUpiDesc: "भुगतान के लिए क्यूआर कोड स्कैन करें या नीचे यूपीआई आईडी कॉपी करें, फिर अपना ऑर्डर दें — हम व्हाट्सएप पर आपके भुगतान की पुष्टि करेंगे।",
    demoQrLabel: "डेमो क्यूआर · असली यूपीआई क्यूआर से बदलें",
    upiIdLabel: "यूपीआई आईडी",
    phoneNumberLabel: "फ़ोन नंबर",
    copy: "कॉपी करें",
    copied: "कॉपी हो गया",
    gotItContinue: "समझ गया, जारी रखें",
    customEnquiryTitle: "कस्टम केटरिंग पूछताछ",
    customEnquiryDesc: "अपने इवेंट के बारे में हमें बताएं और हम व्हाट्सएप पर कस्टम मेन्यू और कीमत के साथ जवाब देंगे।",
    eventType: "इवेंट का प्रकार",
    birthdayParty: "जन्मदिन पार्टी",
    corporateEvent: "कॉर्पोरेट इवेंट",
    wedding: "शादी",
    houseParty: "हाउस पार्टी",
    otherOccasion: "अन्य",
    dishesInterested: "जिन व्यंजनों में आप रुचि रखते हैं",
    dishesInterestedPlaceholder: "जैसे: मोमो प्लेटर, बिरयानी, चाउमीन, बर्गर...",
    numberOfPeople: "लोगों की संख्या",
    numberOfPeoplePlaceholder: "जैसे: 20-25 लोग",
    preferredDateTimeLabel: "पसंदीदा तारीख और समय",
    chooseDate: "तारीख चुनें",
    chooseTime: "समय चुनें",
    specialInstructions: "विशेष निर्देश",
    optional: "वैकल्पिक",
    specialInstructionsPlaceholder: "आहार प्रतिबंध, पसंदीदा व्यंजन, डिलीवरी नोट्स, आदि।",
    sendEnquiryWhatsapp: "व्हाट्सएप पर पूछताछ भेजें",
    toastAddedToCart: "{name} कार्ट में जोड़ा गया",
    toastItemRemoved: "आइटम हटाया गया",
    toastCartCleared: "कार्ट खाली किया गया",
    toastFillDetails: "कृपया नाम, फ़ोन और पता भरें",
    toastInvalidPhone: "कृपया एक मान्य 10-अंकीय फ़ोन नंबर दर्ज करें",
    toastCartEmptyRetry: "आपका कार्ट खाली है। कृपया फिर से आइटम जोड़ें।",
    toastEnterLocation: "कृपया अपना स्थान दर्ज करें",
    toastLocationSaved: "स्थान सहेजा गया",
    toastNoGeolocation: "इस डिवाइस पर लोकेशन सेवाएं समर्थित नहीं हैं",
    toastLocationUpdated: "स्थान अपडेट किया गया: {label}",
    toastLocationDenied: "स्वतः पता लगाने के लिए कृपया स्थान की अनुमति दें",
    toastLocationFailed: "स्थान का पता नहीं चल सका, स्वयं दर्ज करके देखें",
    toastAppAlreadyInstalled: "ऐप पहले से इंस्टॉल है या यह ब्राउज़र समर्थित नहीं है",
    toastInstalling: "स्वादेर घर इंस्टॉल हो रहा है...",
    toastOpeningWhatsappEnquiry: "आपकी पूछताछ के साथ व्हाट्सएप खोला जा रहा है...",
    toastLanguageUpdated: "भाषा अपडेट की गई",
    toastDemoQr: "डेमो क्यूआर — इसे अपने असली यूपीआई क्यूआर कोड से बदलें",
    toastCopied: "क्लिपबोर्ड पर कॉपी किया गया",
    toastCopyFailed: "कॉपी नहीं हो सका — कृपया मैन्युअल रूप से कॉपी करें",
    toastInstalled: "स्वादेर घर सफलतापूर्वक इंस्टॉल हो गया!",
    toastNewVersion: "नया संस्करण उपलब्ध है",
    toastTapToRefresh: "रिफ्रेश करने के लिए टैप करें",
    toastCoordsInvalid: "कृपया \"lat, lng\" के रूप में मान्य निर्देशांक दर्ज करें",
    toastCoordsUpdated: "डिलीवरी निर्देशांक अपडेट किए गए",
    totalLabel: "कुल",
    decreaseQtyAria: "मात्रा घटाएं",
    increaseQtyAria: "मात्रा बढ़ाएं",
    itemCount: "{n} आइटम",
    itemCountPlural: "{n} आइटम",
    onwards: "से शुरू",
  },
};
